name: Alpine

on: push

jobs:
  alpine:
    runs-on: ubuntu-24.04
    container: 'alpine:3.20'
    steps:
      - name: Install and prepare Git
        run: |
          apk update && apk upgrade
          apk add git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          apk update
          apk add catch2 cmake curl-dev fortune g++ git make pkgconf sqlite-dev
      - name: Build
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          cmake ../
          cmake --build . -j2
      - name: Run tests
        run: |
          cd "$GITHUB_WORKSPACE/build"
          ctest -V
      - name: Install statically linked libraries
        run: |
          apk add brotli-static c-ares-static curl-static libidn2-static
          apk add libpsl-static libunistring-static nghttp2-static
          apk add openssl-libs-static sqlite-static zlib-static zstd-static
      - name: Build statically linked executable
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir build-static
          cd build-static
          export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON
          cmake --build . -j2
      - name: Run tests for statically linked build
        run: |
          cd "$GITHUB_WORKSPACE/build-static"
          ctest -V
      - name: Collect build artifacts
        run: |
          mkdir -p "$GITHUB_WORKSPACE"/artifacts
          cd "$GITHUB_WORKSPACE"
          # binary file
          cp build-static/src/botvinnik/botvinnik artifacts/
          # license + changelog
          cp LICENSE artifacts/
          cp changelog.md artifacts/
          # documentation files
          cp doc/*.md artifacts/
          # remove build instructions for Windows
          unlink artifacts/msys2-build.md
          # determine version
          VERSION=$(git describe --always)
          echo Version is $VERSION.
          mv artifacts botvinnik-$VERSION
          tar czf botvinnik_${VERSION}_linux-amd64-generic.tar.gz botvinnik-$VERSION
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: botvinnik_linux-amd64-generic
          path: botvinnik_*_linux-amd64-generic.tar.gz
          if-no-files-found: error
