name: Clang

on: push

jobs:
  build_ubuntu_clang:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version: [7, 8, 9, 10, 11]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake fortune-mod fortunes-min clang-${{ matrix.version }} git libcurl4-gnutls-dev libsqlite3-dev pkg-config
      - name: Install LLVM C++ Standard Library
        run: |
          sudo apt-get install -y libc++-${{ matrix.version }}-dev
        if: matrix.version == 8
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Build with Clang ${{ matrix.version }} with User-Agent
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          # Build with User-Agent header.
          mkdir ./build-with-ua
          cd ./build-with-ua
          cmake -DUSER_AGENT=ON ../
          make -j4
          cd ..
        if: matrix.version == 10
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
