name: GitHub CI with GCC 8, 9, 10

on: push

jobs:
  build_ubuntu_gcc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [8, 9, 10, 11]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake fortune-mod fortunes-min g++-${{ matrix.version }} git libcurl4-gnutls-dev libsqlite3-dev pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Build with GNU GCC ${{ matrix.version }} with User-Agent
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          # Build with User-Agent header.
          mkdir ./build-with-ua
          cd ./build-with-ua
          cmake -DUSER_AGENT=ON ../
          make -j4
          cd ..
        if: matrix.version == 10
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
