name: Clang

on: push

jobs:
  clang:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 11
            os: ubuntu-22.04
          - version: 12
            os: ubuntu-22.04
          - version: 13
            os: ubuntu-22.04
          - version: 14
            os: ubuntu-24.04
          - version: 15
            os: ubuntu-24.04
          - version: 16
            os: ubuntu-24.04
          - version: 17
            os: ubuntu-24.04
          - version: 18
            os: ubuntu-24.04
          - version: 19
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake fortune-mod fortunes-min clang-${{ matrix.version }} git libcurl4-gnutls-dev libsqlite3-dev pkg-config
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Build with Clang ${{ matrix.version }} with User-Agent
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          # Build with User-Agent header.
          mkdir ./build-with-ua
          cd ./build-with-ua
          cmake -DUSER_AGENT=ON ../
          make -j2
          cd ..
        if: matrix.version == 14
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
