name: Clang

on: push

jobs:
  clang:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 11
            os: ubuntu-22.04
          - version: 12
            os: ubuntu-22.04
          - version: 13
            os: ubuntu-22.04
          - version: 14
            os: ubuntu-24.04
          - version: 15
            os: ubuntu-24.04
          - version: 16
            os: ubuntu-24.04
          - version: 17
            os: ubuntu-24.04
          - version: 18
            os: ubuntu-24.04
          - version: 19
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Git checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake fortune-mod fortunes-min clang-${{ matrix.version }} git libcurl4-gnutls-dev libsqlite3-dev pkg-config
      - name: Build with Clang ${{ matrix.version }}
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Build with Clang ${{ matrix.version }} with User-Agent
        run: |
          export CXX=clang++-${{ matrix.version }}
          export CC=clang-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          # Build with User-Agent header.
          mkdir ./build-with-ua
          cd ./build-with-ua
          cmake -DUSER_AGENT=ON ../
          make -j2
          cd ..
        if: matrix.version == 14
      - name: Download Mocktrix as homeserver for tests
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt-get install -y wget tar bzip2
          wget https://github.com/striezel/Mocktrix/releases/download/v0.1.0/Mocktrix-v0.1.0-linux-x64-self-contained.tar.bz2
          CHECKSUM=$(sha256sum Mocktrix-v0.1.0-linux-x64-self-contained.tar.bz2)
          echo "Checksum calculation: $CHECKSUM"
          CHECKSUM_BITS=$(echo $CHECKSUM | cut -c1-64)
          if [ "$CHECKSUM_BITS" != "f95a0928d0f8d7b22f3729021d1de12e06812e6ff48b9adcb399be27dcf95833" ]
          then
            echo "Checksum of downloaded homeserver is wrong."
            exit 1
          fi
          tar xf Mocktrix-v0.1.0-linux-x64-self-contained.tar.bz2
      - name: Start Mocktrix homeserver for tests
        run: |
          cd "$GITHUB_WORKSPACE/Mocktrix-v0.1.0-linux-x64-self-contained"
          ./Mocktrix &
          while ! netstat -tna | grep LISTEN | grep --silent 5000
          do
              echo Waiting for Kestrel server to start ...
              sleep 5
          done
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
