name: Build Dockerfile

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Git checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Build image from Dockerfile
        run: |
          cd "$GITHUB_WORKSPACE"
          docker build . -t botvinnik
