name: Sanitizers

on: push

jobs:
  sanitizer:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 14
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 cmake fortune-mod fortunes-min g++-${{ matrix.version }} git libcurl4-gnutls-dev libsqlite3-dev pkg-config
          sudo apt-get install -y libasan8 libubsan1
      - name: Build with GNU GCC ${{ matrix.version }} and sanitizers enabled
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../ -DENABLE_SANITIZER=ON
          make -j2
      - name: Download Mocktrix as homeserver for tests
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt-get install -y wget tar bzip2
          wget https://github.com/striezel/Mocktrix/releases/download/v0.1.0/Mocktrix-v0.1.0-linux-x64-self-contained.tar.bz2
          CHECKSUM=$(sha256sum Mocktrix-v0.1.0-linux-x64-self-contained.tar.bz2)
          echo "Checksum calculation: $CHECKSUM"
          CHECKSUM_BITS=$(echo $CHECKSUM | cut -c1-64)
          if [ "$CHECKSUM_BITS" != "f95a0928d0f8d7b22f3729021d1de12e06812e6ff48b9adcb399be27dcf95833" ]
          then
            echo "Checksum of downloaded homeserver is wrong."
            exit 1
          fi
          tar xf Mocktrix-v0.1.0-linux-x64-self-contained.tar.bz2
      - name: Start Mocktrix homeserver for tests
        run: |
          cd "$GITHUB_WORKSPACE/Mocktrix-v0.1.0-linux-x64-self-contained"
          ./Mocktrix &
          while ! netstat -tna | grep LISTEN | grep --silent 5000
          do
              echo Waiting for Kestrel server to start ...
              sleep 5
          done
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
