name: Ubuntu 18.04 with GNU GCC 8

on: push

jobs:
  build_ubuntu_18_04_gcc8:
    runs-on: ubuntu-18.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake fortune-mod fortunes-min g++-8 git libcurl4-gnutls-dev libsqlite3-dev pkg-config
      - name: Build
        run: |
          export CXX=g++-8
          export CC=gcc-8
          cd $GITHUB_WORKSPACE && pwd && ls -lah
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
