name: Ubuntu 20.04 with Clang 10

on: push

jobs:
  build_ubuntu_20_04_clang10:
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake fortune-mod fortunes-min clang-10 git libcurl4-gnutls-dev libsqlite3-dev pkg-config
      - name: Build
        run: |
          export CXX=clang++-10
          export CC=clang-10
          cd $GITHUB_WORKSPACE && pwd && ls -lah
          mkdir build
          cd build
          cmake ../
          make -j4
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
